import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css'

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <header className='bg-red-400 text-center py-8'>
          <p>この表示はheaderタグに記載したテキストです。</p>
        </header>
        <main>{children}</main>
        <footer className='bg-blue-400 text-center py-8'>
          <p>この表示はfooterタグに記載したテキストです。</p>
        </footer>
      </body>
    </html>
  );
}
